if(NOT EXECUTABLE_NAME)
  set(EXECUTABLE_NAME "${CMAKE_PROJECT_NAME}")
endif()

set_target_properties("${CMAKE_PROJECT_NAME}" PROPERTIES
  OUTPUT_NAME "${EXECUTABLE_NAME}")

add_custom_target(run
  COMMAND "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${EXECUTABLE_NAME}"
  DEPENDS "${CMAKE_PROJECT_NAME}"
  )
